In [5]:
import numpy as np
import sys

'''WHY IS NUMPY FAST?
-Fixed type: and contiguous memory
numpy stores as int 32 (4 bytes) no type checking
lists stores (size,reference count,object type,object value)=lot more memory
numpy reads less bytes of memory
list stores in pointer to block of memory (not together)
where as numpy uses contiguous memory stored together: know starting and size rather than pointers.'''

**THE BASICS**

In [21]:
a = np.array([1,2,3],dtype = 'int16')
print(a)

[1 2 3]


In [12]:
b = np.array([[9,0,2,3],[4,5,7,1]])
print(b)

[[9 0 2 3]
 [4 5 7 1]]


In [14]:
#Get the dimensions
a.ndim

1

In [17]:
#Get the shape 
a.shape

(3,)

In [19]:
print(b.ndim)
print(b.shape)

2
(2, 4)


In [22]:
#Get the type
a.dtype

dtype('int16')

In [24]:
#Get the size (this returns the byte)
a.itemsize

2

**Accessing /changingin specific elements,rows and colomns**

In [26]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [28]:
#Get a specific element [r,c]
print(a[1,5])

13


In [30]:
#Get a specific row
print(a[0,:])

[1 2 3 4 5 6 7]


In [31]:
#Get a specific column
print(a[:,3])

[ 4 11]


In [35]:
#Getting a little more fancy[startindex:endindex:step]
print(a[1,1:5:2])

[ 9 11]


In [36]:
a[1,5]= 20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [37]:
#Modifying entire series
a[:,2] = 5
print(a)

[[ 1  2  5  4  5  6  7]
 [ 8  9  5 11 12 20 14]]


In [38]:
a[:,4]= [1,2]
print(a)

[[ 1  2  5  4  1  6  7]
 [ 8  9  5 11  2 20 14]]


In [ ]:
#3dimensional array

In [42]:
b = np.array([
    [[1,2],[3,4]],
    [[5,6],[7,8]]
])
print(b)
print(b.size)
print(b.ndim)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
8
3


In [45]:
#Get specific element(work outside in)
print(b[0,1,1])

4


In [47]:
print(b[0,:,0])

[1 3]


In [48]:
 print(b[:,1,:])

[[3 4]
 [7 8]]


In [49]:
b[:,1,:]=[[20,30],[10,15]]
print(b)

[[[ 1  2]
  [20 30]]

 [[ 5  6]
  [10 15]]]


**Initializing different types of array**

In [51]:
#All 0's matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [57]:
c = np.zeros((3,4,5))
print(c)

[[[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]

 [[0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]
  [0. 0. 0. 0. 0.]]]


In [59]:
np.ones((4,2,2),dtype= 'int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [61]:
#any other number
np.full((2,2),99,dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [62]:
#any other number (full_like) the shape of previous defined array
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [66]:
np.random.rand(4,2)

array([[0.01024026, 0.50610294],
       [0.75276475, 0.13539975],
       [0.46884408, 0.25629934],
       [0.77937776, 0.17583843]])

In [71]:
np.random.randint(2,27,size=(3,3))

array([[11,  6, 21],
       [12, 16,  5],
       [13, 13, 20]])

In [72]:
#identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [74]:
#repeat an array
arr = np.array([[1,2,3]])
rep = np.repeat(arr,3,axis =0)
print(rep)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [78]:
a = np.ones((5,5),dtype='int16')
print(a)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [86]:
z = np.zeros((3,3),dtype='int16')
z[1,1]=9
a[1:4,1:4]=z
print(a)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


**BE CAREFUL COPYING ARRAYS**

In [93]:
a = np.array([1,2,3])
b = a
b[0] = 100
print(a)
print(b)
#variable name b is now a so be careful

[100   2   3]
[100   2   3]


In [95]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)
print(b)
#using .copy() will only copy the values not the variable name

[1 2 3]
[100   2   3]


**MATHEMATICS**

In [96]:
a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [97]:
a + 2

array([3, 4, 5, 6])

In [98]:
a-2

array([-1,  0,  1,  2])

In [99]:
a*2

array([2, 4, 6, 8])

In [100]:
a/2

array([0.5, 1. , 1.5, 2. ])

In [101]:
b = np.array([1,0,1,0])
a+b

array([2, 2, 4, 4])

In [103]:
a **2

array([ 1,  4,  9, 16])

In [104]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [105]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

**LINEAR ALGEBRA**

In [113]:
a = np.ones((2,3))
b = np.full((3,2),2)
print(a)
print(b)

np.matmul(a,b)

[[1. 1. 1.]
 [1. 1. 1.]]
[[2 2]
 [2 2]
 [2 2]]


array([[6., 6.],
       [6., 6.]])

In [115]:
c = np.identity(3)
print(c)
np.linalg.det(c)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


np.float64(1.0)

 **STATISTICS**


In [116]:
stats = np.array([[1,2,3],[4,5,6]])
print(stats)

[[1 2 3]
 [4 5 6]]


In [124]:
np.min((stats),axis= 1)

array([1, 4])

In [119]:
print(np.max(stats))

6


In [125]:
np.sum(stats)

np.int64(21)

**REORGANIZING ARRAYS**

In [127]:
before = np.array([[1,2,3,4],[5,6,7,8]])
before.shape

(2, 4)

In [130]:
after = before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [132]:
#Vertical Stacking vectors

In [134]:
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])
np.vstack([v1,v2,v1])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4]])

In [136]:
#Horizontal Stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))
np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

**MISCELLANOUS**


In [137]:
#LOAD DATA FROM FILE

In [145]:
filedata = np.genfromtxt('data.txt',delimiter=',')
filedata = filedata.astype('int32')
print(filedata)
                

[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


**BOOLEAN MASKING AND ADVANCED INDEXING**

In [146]:
filedata > 50

array([[False, False, False, False,  True,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False,  True, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [147]:
filedata[filedata>50]

array([196,  75, 766,  75,  55, 999,  78,  76,  88], dtype=int32)

In [148]:
#you can index with a list in numpy

In [151]:
a = np.array([1,2,3,4,5,6,7,8,9])
a[[1,2,8]]

array([2, 3, 9])

In [152]:
np.any(filedata>50,axis = 0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [153]:
np.all(filedata>50,axis = 0)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False, False, False, False, False, False])

In [159]:
((filedata > 50) & (filedata<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [162]:
arr = np.arange(1, 31).reshape(6, 5)
arr[2:4,0:2]

array([[11, 12],
       [16, 17]])

In [163]:
arr[[0,1,2,3],[1,2,3,4]]

array([ 2,  8, 14, 20])

In [164]:
arr[[0,4,5],3:]

array([[ 4,  5],
       [24, 25],
       [29, 30]])